# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += core gui network webchannel webengine webenginewidgets widgets

TEMPLATE = app
TARGET = Almighty
DESTDIR = ../x64/Release
CONFIG += release
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(Almighty.pri)
